<?php
/**
 * ShareMessageWithOtherUserLanguage
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  IONOS\MailNotificationAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Event Notification Handler
 *
 * Event Notification Handler
 *
 * The version of the OpenAPI document: 1.0.0-20240927113522
 * Contact: saas-dev@1und1.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace IONOS\MailNotificationAPI\Client\Model;

use \ArrayAccess;
use \IONOS\MailNotificationAPI\Client\ObjectSerializer;

/**
 * ShareMessageWithOtherUserLanguage Class Doc Comment
 *
 * @category Class
 * @description Language preference for the notification. If not set, market Locale of contract is selected.
 * @package  IONOS\MailNotificationAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShareMessageWithOtherUserLanguage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShareMessageWithOtherUser_language';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'language' => 'string',
        'display_name' => 'string',
        'country' => 'string',
        'variant' => 'string',
        'script' => 'string',
        'unicode_locale_attributes' => 'string[]',
        'unicode_locale_keys' => 'string[]',
        'display_language' => 'string',
        'display_script' => 'string',
        'display_country' => 'string',
        'display_variant' => 'string',
        'extension_keys' => 'string[]',
        'iso3_language' => 'string',
        'iso3_country' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'language' => null,
        'display_name' => null,
        'country' => null,
        'variant' => null,
        'script' => null,
        'unicode_locale_attributes' => null,
        'unicode_locale_keys' => null,
        'display_language' => null,
        'display_script' => null,
        'display_country' => null,
        'display_variant' => null,
        'extension_keys' => null,
        'iso3_language' => null,
        'iso3_country' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'language' => false,
        'display_name' => false,
        'country' => false,
        'variant' => false,
        'script' => false,
        'unicode_locale_attributes' => false,
        'unicode_locale_keys' => false,
        'display_language' => false,
        'display_script' => false,
        'display_country' => false,
        'display_variant' => false,
        'extension_keys' => false,
        'iso3_language' => false,
        'iso3_country' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'language' => 'language',
        'display_name' => 'displayName',
        'country' => 'country',
        'variant' => 'variant',
        'script' => 'script',
        'unicode_locale_attributes' => 'unicodeLocaleAttributes',
        'unicode_locale_keys' => 'unicodeLocaleKeys',
        'display_language' => 'displayLanguage',
        'display_script' => 'displayScript',
        'display_country' => 'displayCountry',
        'display_variant' => 'displayVariant',
        'extension_keys' => 'extensionKeys',
        'iso3_language' => 'iso3Language',
        'iso3_country' => 'iso3Country'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'language' => 'setLanguage',
        'display_name' => 'setDisplayName',
        'country' => 'setCountry',
        'variant' => 'setVariant',
        'script' => 'setScript',
        'unicode_locale_attributes' => 'setUnicodeLocaleAttributes',
        'unicode_locale_keys' => 'setUnicodeLocaleKeys',
        'display_language' => 'setDisplayLanguage',
        'display_script' => 'setDisplayScript',
        'display_country' => 'setDisplayCountry',
        'display_variant' => 'setDisplayVariant',
        'extension_keys' => 'setExtensionKeys',
        'iso3_language' => 'setIso3Language',
        'iso3_country' => 'setIso3Country'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'language' => 'getLanguage',
        'display_name' => 'getDisplayName',
        'country' => 'getCountry',
        'variant' => 'getVariant',
        'script' => 'getScript',
        'unicode_locale_attributes' => 'getUnicodeLocaleAttributes',
        'unicode_locale_keys' => 'getUnicodeLocaleKeys',
        'display_language' => 'getDisplayLanguage',
        'display_script' => 'getDisplayScript',
        'display_country' => 'getDisplayCountry',
        'display_variant' => 'getDisplayVariant',
        'extension_keys' => 'getExtensionKeys',
        'iso3_language' => 'getIso3Language',
        'iso3_country' => 'getIso3Country'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('variant', $data ?? [], null);
        $this->setIfExists('script', $data ?? [], null);
        $this->setIfExists('unicode_locale_attributes', $data ?? [], null);
        $this->setIfExists('unicode_locale_keys', $data ?? [], null);
        $this->setIfExists('display_language', $data ?? [], null);
        $this->setIfExists('display_script', $data ?? [], null);
        $this->setIfExists('display_country', $data ?? [], null);
        $this->setIfExists('display_variant', $data ?? [], null);
        $this->setIfExists('extension_keys', $data ?? [], null);
        $this->setIfExists('iso3_language', $data ?? [], null);
        $this->setIfExists('iso3_country', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            throw new \InvalidArgumentException('non-nullable display_name cannot be null');
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets country
     *
     * @return string|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param string|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets variant
     *
     * @return string|null
     */
    public function getVariant()
    {
        return $this->container['variant'];
    }

    /**
     * Sets variant
     *
     * @param string|null $variant variant
     *
     * @return self
     */
    public function setVariant($variant)
    {
        if (is_null($variant)) {
            throw new \InvalidArgumentException('non-nullable variant cannot be null');
        }
        $this->container['variant'] = $variant;

        return $this;
    }

    /**
     * Gets script
     *
     * @return string|null
     */
    public function getScript()
    {
        return $this->container['script'];
    }

    /**
     * Sets script
     *
     * @param string|null $script script
     *
     * @return self
     */
    public function setScript($script)
    {
        if (is_null($script)) {
            throw new \InvalidArgumentException('non-nullable script cannot be null');
        }
        $this->container['script'] = $script;

        return $this;
    }

    /**
     * Gets unicode_locale_attributes
     *
     * @return string[]|null
     */
    public function getUnicodeLocaleAttributes()
    {
        return $this->container['unicode_locale_attributes'];
    }

    /**
     * Sets unicode_locale_attributes
     *
     * @param string[]|null $unicode_locale_attributes unicode_locale_attributes
     *
     * @return self
     */
    public function setUnicodeLocaleAttributes($unicode_locale_attributes)
    {
        if (is_null($unicode_locale_attributes)) {
            throw new \InvalidArgumentException('non-nullable unicode_locale_attributes cannot be null');
        }


        $this->container['unicode_locale_attributes'] = $unicode_locale_attributes;

        return $this;
    }

    /**
     * Gets unicode_locale_keys
     *
     * @return string[]|null
     */
    public function getUnicodeLocaleKeys()
    {
        return $this->container['unicode_locale_keys'];
    }

    /**
     * Sets unicode_locale_keys
     *
     * @param string[]|null $unicode_locale_keys unicode_locale_keys
     *
     * @return self
     */
    public function setUnicodeLocaleKeys($unicode_locale_keys)
    {
        if (is_null($unicode_locale_keys)) {
            throw new \InvalidArgumentException('non-nullable unicode_locale_keys cannot be null');
        }


        $this->container['unicode_locale_keys'] = $unicode_locale_keys;

        return $this;
    }

    /**
     * Gets display_language
     *
     * @return string|null
     */
    public function getDisplayLanguage()
    {
        return $this->container['display_language'];
    }

    /**
     * Sets display_language
     *
     * @param string|null $display_language display_language
     *
     * @return self
     */
    public function setDisplayLanguage($display_language)
    {
        if (is_null($display_language)) {
            throw new \InvalidArgumentException('non-nullable display_language cannot be null');
        }
        $this->container['display_language'] = $display_language;

        return $this;
    }

    /**
     * Gets display_script
     *
     * @return string|null
     */
    public function getDisplayScript()
    {
        return $this->container['display_script'];
    }

    /**
     * Sets display_script
     *
     * @param string|null $display_script display_script
     *
     * @return self
     */
    public function setDisplayScript($display_script)
    {
        if (is_null($display_script)) {
            throw new \InvalidArgumentException('non-nullable display_script cannot be null');
        }
        $this->container['display_script'] = $display_script;

        return $this;
    }

    /**
     * Gets display_country
     *
     * @return string|null
     */
    public function getDisplayCountry()
    {
        return $this->container['display_country'];
    }

    /**
     * Sets display_country
     *
     * @param string|null $display_country display_country
     *
     * @return self
     */
    public function setDisplayCountry($display_country)
    {
        if (is_null($display_country)) {
            throw new \InvalidArgumentException('non-nullable display_country cannot be null');
        }
        $this->container['display_country'] = $display_country;

        return $this;
    }

    /**
     * Gets display_variant
     *
     * @return string|null
     */
    public function getDisplayVariant()
    {
        return $this->container['display_variant'];
    }

    /**
     * Sets display_variant
     *
     * @param string|null $display_variant display_variant
     *
     * @return self
     */
    public function setDisplayVariant($display_variant)
    {
        if (is_null($display_variant)) {
            throw new \InvalidArgumentException('non-nullable display_variant cannot be null');
        }
        $this->container['display_variant'] = $display_variant;

        return $this;
    }

    /**
     * Gets extension_keys
     *
     * @return string[]|null
     */
    public function getExtensionKeys()
    {
        return $this->container['extension_keys'];
    }

    /**
     * Sets extension_keys
     *
     * @param string[]|null $extension_keys extension_keys
     *
     * @return self
     */
    public function setExtensionKeys($extension_keys)
    {
        if (is_null($extension_keys)) {
            throw new \InvalidArgumentException('non-nullable extension_keys cannot be null');
        }


        $this->container['extension_keys'] = $extension_keys;

        return $this;
    }

    /**
     * Gets iso3_language
     *
     * @return string|null
     */
    public function getIso3Language()
    {
        return $this->container['iso3_language'];
    }

    /**
     * Sets iso3_language
     *
     * @param string|null $iso3_language iso3_language
     *
     * @return self
     */
    public function setIso3Language($iso3_language)
    {
        if (is_null($iso3_language)) {
            throw new \InvalidArgumentException('non-nullable iso3_language cannot be null');
        }
        $this->container['iso3_language'] = $iso3_language;

        return $this;
    }

    /**
     * Gets iso3_country
     *
     * @return string|null
     */
    public function getIso3Country()
    {
        return $this->container['iso3_country'];
    }

    /**
     * Sets iso3_country
     *
     * @param string|null $iso3_country iso3_country
     *
     * @return self
     */
    public function setIso3Country($iso3_country)
    {
        if (is_null($iso3_country)) {
            throw new \InvalidArgumentException('non-nullable iso3_country cannot be null');
        }
        $this->container['iso3_country'] = $iso3_country;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


