<?php
/**
 * EventAPIApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  IONOS\MailNotificationAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Event Notification Handler
 *
 * Event Notification Handler
 *
 * The version of the OpenAPI document: 1.0.0-20240927113522
 * Contact: saas-dev@1und1.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace IONOS\MailNotificationAPI\Client\Test\Api;

use \IONOS\MailNotificationAPI\Client\Configuration;
use \IONOS\MailNotificationAPI\Client\ApiException;
use \IONOS\MailNotificationAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EventAPIApiTest Class Doc Comment
 *
 * @category Class
 * @package  IONOS\MailNotificationAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EventAPIApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for processRemoteWipeFinishedEvent
     *
     * Nextlcoud user gets informed that a remote wipe for a specific device has finished.
     *
     */
    public function testProcessRemoteWipeFinishedEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processRemoteWipeStartedEvent
     *
     * Nextlcoud user started a remote wipe for a specific device.
     *
     */
    public function testProcessRemoteWipeStartedEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processShareByLinkEvent
     *
     * Nextlcoud user shared a file with other users via list of receiver email addresses.
     *
     */
    public function testProcessShareByLinkEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for processShareWithOtherUsersEvent
     *
     * Nextlcoud user shared a file with other users via list of receiver user ids in uuid format.
     *
     */
    public function testProcessShareWithOtherUsersEvent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
